services:
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    ports:
      - "8081:80"            # ⬅️ Graphite UI moved from 80 → 8081
      - "2003-2004:2003-2004"
      - "8125:8125/udp"
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"          # Grafana UI still on 3001
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - graphite
    restart: always
